# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20161116_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfSelectedTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('stockcode', models.CharField(max_length=6, verbose_name='股票代码')),
                ('groupname', models.CharField(blank=True, max_length=20, verbose_name='自选股编组')),
            ],
        ),
    ]
