# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20161116_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbriefinfotbl',
            name='subjects',
            field=models.CharField(blank=True, max_length=40, verbose_name='题材概念板块'),
        ),
    ]
