# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20161116_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbriefinfotbl',
            name='industry',
            field=models.CharField(blank=True, max_length=20, verbose_name='所属行业 '),
        ),
    ]
