# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_delete_stockbriefinfotbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBriefInfoTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.CharField(max_length=6, verbose_name='股票代码')),
                ('stockname', models.CharField(max_length=8, verbose_name='股票简称')),
                ('stockpy', models.CharField(max_length=4, verbose_name='股票拼音')),
                ('industry', models.CharField(blank=True, max_length=20, verbose_name='所属行业 ')),
                ('subjects', models.CharField(blank=True, max_length=40, verbose_name='题材概念板块')),
            ],
        ),
    ]
