# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_stockbriefinfotbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbriefinfotbl',
            name='industry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='stockbriefinfotbl',
            name='subjects',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='题材概念板块'),
        ),
    ]
