# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20161116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hzpytbl',
            name='hz',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='汉字'),
        ),
        migrations.AlterField(
            model_name='reportdownloadsinfotbl',
            name='filename',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='reportdownloadsinfotbl',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='selfselectedtbl',
            name='groupname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='自选股编组'),
        ),
    ]
