# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20161116_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbriefinfotbl',
            name='stockpy',
            field=models.CharField(max_length=6, verbose_name='股票拼音'),
        ),
    ]
