# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_delete_holidaytbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='起始日期')),
                ('end', models.DateField(verbose_name='结束日期')),
                ('memo', models.CharField(max_length=20, verbose_name='节假日说明')),
            ],
        ),
    ]
